// dsh-chat-index client bundle (generated by scripts/build.mjs — edit src/client/*, not this file)
window.__ModuleLoader__.load({
	id: "dsh-chat-index",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
  //#region src/client/00-libs.js
  // Shared libs, evaluated once in the factory closure. Later fragments may use
  // these names directly.
  const ReactLib = require('react');
  // react-dom is resolved lazily/optionally: some embedding surfaces may not
  // seed it, and materialization must not die on an unresolvable require.
  let ReactDOMLib = null;
  try {
  	ReactDOMLib = require('react-dom');
  } catch (err) {
  	console.warn('[dsh-chat-index] react-dom not available, will render inline', err);
  }
  const {
  	useState,
  	useEffect,
  	useRef,
  	useMemo,
  	useCallback,
  	useSyncExternalStore,
  	createElement: h,
  	Fragment,
  } = ReactLib;

  //#endregion
  //#region src/client/01-style.js
  // CSS injection (self-contained; idempotent). Call ensureChatIndexStyle() as
  // soon as the DOM head exists (fragment top level + again from apply()).
  // Every rule is scoped under the plugin's own root attribute so it never
  // reaches product DOM. Colors adapt to the surrounding theme via CSS
  // color-mix() so no product token vocabulary is imported.
  function ensureChatIndexStyle() {
  	if (typeof document === "undefined" || !document.head) return false;
  	if (document.getElementById("dsh-chat-index-style")) return true;
  	const style = document.createElement("style");
  	style.id = "dsh-chat-index-style";
  	style.textContent = `
  [dsh-chat-index-root] {
  	--dshci-accent: color-mix(in srgb, currentColor 55%, transparent);
  	--dshci-rail-w: 26px;
  	--dshci-gap: 10px;
  	position: fixed;
  	z-index: 9000;
  	font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", "Microsoft YaHei", sans-serif;
  	font-size: 13px;
  	line-height: 1.45;
  	color: inherit;
  }
  [dsh-chat-index-root], [dsh-chat-index-root] * { box-sizing: border-box; }

  /* rail (collapsed) */
  [dsh-chat-index-rail] {
  	position: absolute;
  	top: 0; right: 0; bottom: 0;
  	width: var(--dshci-rail-w);
  	pointer-events: auto;
  	display: flex;
  	flex-direction: column;
  	align-items: center;
  	background: color-mix(in srgb, currentColor 9%, transparent);
  	border: 1px solid color-mix(in srgb, currentColor 22%, transparent);
  	border-radius: 8px;
  	opacity: 0.9;
  	transition: opacity 0.18s ease, background 0.18s ease;
  	cursor: pointer;
  	user-select: none;
  	overflow: hidden;
  }
  [dsh-chat-index-rail]:hover { opacity: 1; background: color-mix(in srgb, currentColor 13%, transparent); }

  [dsh-chat-index-rail-head] {
  	width: 100%;
  	text-align: center;
  	padding: 6px 0 2px;
  	font-size: 10px;
  	letter-spacing: 0.5px;
  	opacity: 0.9;
  	writing-mode: vertical-rl;
  	transform: rotate(180deg);
  	text-transform: uppercase;
  	white-space: nowrap;
  }

  /* marker track (scrub area) */
  [dsh-chat-index-track] {
  	position: relative;
  	flex: 1 1 auto;
  	width: 100%;
  	touch-action: none;
  }
  [dsh-chat-index-marker] {
  	position: absolute;
  	left: 50%;
  	transform: translateX(-50%);
  	width: 9px;
  	height: 9px;
  	border-radius: 50%;
  	background: currentColor;
  	opacity: 0.55;
  	box-shadow: 0 0 0 2px color-mix(in srgb, canvas 85%, transparent);
  	transition: width 0.12s ease, height 0.12s ease, opacity 0.12s ease;
  }
  [dsh-chat-index-rail]:hover [dsh-chat-index-marker],
  [dsh-chat-index-marker][dsh-chat-index-live] {
  	opacity: 0.9;
  }
  [dsh-chat-index-marker]:hover {
  	width: 12px;
  	height: 12px;
  	opacity: 1;
  }
  [dsh-chat-index-marker][dsh-chat-index-current] {
  	opacity: 1;
  	box-shadow: 0 0 0 2px color-mix(in srgb, canvas 85%, transparent), 0 0 6px currentColor;
  }
  [dsh-chat-index-thumb] {
  	position: absolute;
  	left: 2px;
  	right: 2px;
  	height: 30px;
  	border-radius: 6px;
  	background: color-mix(in srgb, currentColor 18%, transparent);
  	pointer-events: none;
  }

  /* drag scrub flyout label */
  [dsh-chat-index-flyout] {
  	position: absolute;
  	right: calc(var(--dshci-rail-w) + 10px);
  	transform: translateY(-50%);
  	max-width: 280px;
  	padding: 6px 10px;
  	border-radius: 8px;
  	background: color-mix(in srgb, canvas 92%, currentColor 8%);
  	border: 1px solid color-mix(in srgb, currentColor 18%, transparent);
  	box-shadow: 0 6px 24px rgb(0 0 0 / 0.25);
  	pointer-events: none;
  	white-space: nowrap;
  	overflow: hidden;
  	text-overflow: ellipsis;
  	font-size: 12px;
  }

  /* expansion button */
  [dsh-chat-index-toggle] {
  	width: 100%;
  	border: 0;
  	padding: 4px 0;
  	background: none;
  	cursor: pointer;
  	font-size: 12px;
  	line-height: 1;
  	opacity: 0.85;
  }
  [dsh-chat-index-toggle]:hover { opacity: 1; }

  /* chain panel (expanded) */
  [dsh-chat-index-panel] {
  	position: absolute;
  	top: 0;
  	right: calc(var(--dshci-rail-w) + var(--dshci-gap));
  	bottom: 0;
  	width: min(400px, 46vw);
  	display: flex;
  	flex-direction: column;
  	background: color-mix(in srgb, canvas 96%, currentColor 4%);
  	border: 1px solid color-mix(in srgb, currentColor 14%, transparent);
  	border-radius: 12px;
  	box-shadow: 0 10px 40px rgb(0 0 0 / 0.28);
  	overflow: hidden;
  }
  [dsh-chat-index-panel-head] {
  	display: flex;
  	align-items: center;
  	gap: 8px;
  	padding: 8px 10px;
  	border-bottom: 1px solid color-mix(in srgb, currentColor 12%, transparent);
  	font-weight: 600;
  }
  [dsh-chat-index-panel-body] {
  	flex: 1 1 auto;
  	overflow-y: auto;
  	padding: 8px 6px 14px;
  	overscroll-behavior: contain;
  }
  [dsh-chat-index-node] {
  	--depth: 0;
  	margin-left: calc(var(--depth) * 16px);
  }
  [dsh-chat-index-node-row] {
  	display: flex;
  	gap: 8px;
  	align-items: baseline;
  	padding: 5px 8px;
  	border-radius: 8px;
  	cursor: pointer;
  }
  [dsh-chat-index-node-row]:hover { background: color-mix(in srgb, currentColor 7%, transparent); }
  [dsh-chat-index-node-dot] {
  	flex: none;
  	width: 7px; height: 7px;
  	border-radius: 50%;
  	background: var(--dshci-accent);
  	margin-top: 5px;
  	position: relative;
  }
  [dsh-chat-index-node-text] {
  	flex: 1 1 auto;
  	min-width: 0;
  }
  [dsh-chat-index-node-q] {
  	overflow: hidden;
  	display: -webkit-box;
  	-webkit-line-clamp: 2;
  	-webkit-box-orient: vertical;
  }
  [dsh-chat-index-node-meta] {
  	font-size: 11px;
  	opacity: 0.65;
  	margin-top: 1px;
  }
  [dsh-chat-index-node-children] {
  	margin-top: 2px;
  }
  [dsh-chat-index-branch-tag {
  	font-size: 10px;
  	padding: 0 5px;
  	border-radius: 999px;
  	background: color-mix(in srgb, currentColor 12%, transparent);
  	margin-right: 6px;
  	white-space: nowrap;
  }

  /* flash highlight for the target message (product message row we can't own —
     applied as a class by our locate code and removed after the animation) */
  [dsh-chat-index-flash] {
  	animation: dshci-flash 1.4s ease-out;
  }
  @keyframes dshci-flash {
  	0% { box-shadow: inset 0 0 0 9999px color-mix(in srgb, currentColor 12%, transparent); }
  	60% { box-shadow: inset 0 0 0 9999px color-mix(in srgb, currentColor 12%, transparent); }
  	100% { box-shadow: inset 0 0 0 0 transparent; }
  }
  `;
  	document.head.appendChild(style);
  	return true;
  }
  ensureChatIndexStyle();

  //#endregion
  //#region src/client/02-utils.js
  // Pure helpers shared by the rail/panel components (no ctx / no host deps).
  function plainTextOf(blocks) {
  	if (!Array.isArray(blocks)) return '';
  	let text = '';
  	for (const b of blocks) {
  		if (b && b.type === 'text' && typeof b.text === 'string') text += b.text;
  	}
  	text = text.replace(/\s+/g, ' ').trim();
  	if (!text) {
  		const hasImage = Array.isArray(blocks) && blocks.some((b) => b && b.type === 'image');
  		const hasTool = Array.isArray(blocks) && blocks.some((b) => b && (b.type === 'tool-result' || b.type === 'tool-call'));
  		if (hasImage) return '[图片]';
  		if (hasTool) return '[工具]';
  		return '(空消息)';
  	}
  	return text.length > 200 ? text.slice(0, 200) + '…' : text;
  }

  function pad2(n) { return n < 10 ? '0' + n : String(n); }

  function formatTime(ms) {
  	if (!(ms > 0)) return '';
  	const d = new Date(ms);
  	const now = new Date();
  	const sameDay = d.toDateString() === now.toDateString();
  	const hm = pad2(d.getHours()) + ':' + pad2(d.getMinutes());
  	if (sameDay) return hm;
  	const md = pad2(d.getMonth() + 1) + '-' + pad2(d.getDate());
  	if (d.getFullYear() === now.getFullYear()) return md + ' ' + hm;
  	return d.getFullYear() + '-' + md + ' ' + hm;
  }

  function conversationColumn() {
  	return document.querySelector('[data-slot="conversation"]');
  }

  // Geometry of the conversation column. The slot node itself can be a 0-size
  // outlet, so prefer the larger of the node and its parent (better-sidebar
  // measures `#root [data-slot="conversation"]` and takes .parentElement for the
  // same reason). Falls back to the whole viewport so the rail always has
  // somewhere to render.
  function measureBox() {
  	const col = conversationColumn();
  	if (col) {
  		let el = col;
  		const own = col.getBoundingClientRect();
  		const par = col.parentElement;
  		if (par) {
  			const pr = par.getBoundingClientRect();
  			if ((pr.width || 0) * (pr.height || 0) >= (own.width || 0) * (own.height || 0)) el = par;
  		}
  		const r = el.getBoundingClientRect();
  		if (r.width > 0 && r.height > 0 && r.bottom > r.top) {
  			return {
  				left: r.left, top: r.top, right: r.right, bottom: r.bottom,
  				width: r.width, height: r.height,
  			};
  		}
  	}
  	return { left: 0, top: 0, right: window.innerWidth, bottom: window.innerHeight, width: window.innerWidth, height: window.innerHeight };
  }

  // Map message seq -> chat view node (kind 'user' / 'steering') from a live
  // ChatSnapshot (useSession(s => s.chat)); returns array of view nodes sorted
  // by seq.
  function questionViewNodes(chat) {
  	if (!chat || !chat.nodes) return [];
  	const out = [];
  	for (const node of chat.nodes.values()) {
  		if (!node) continue;
  		if (node.kind === 'user' || node.kind === 'steering') {
  			const seq = node.data && typeof node.data.seq === 'number' ? node.data.seq : node.anchorSeq;
  			if (typeof seq === 'number') out.push({ key: node.key, kind: node.kind, seq });
  		}
  	}
  	out.sort((a, b) => a.seq - b.seq);
  	return out;
  }

  function seqToAnchorKey(chat, seq) {
  	for (const node of chat.nodes.values()) {
  		if (!node) continue;
  		const nseq = node.data && typeof node.data.seq === 'number' ? node.data.seq : node.anchorSeq;
  		if (nseq === seq && (node.kind === 'user' || node.kind === 'steering')) return node.key;
  	}
  	return null;
  }

  function rowByAnchorKey(key) {
  	if (!key) return null;
  	const esc = (typeof CSS !== 'undefined' && CSS.escape)
  		? CSS.escape
  		: (s) => String(s).replace(/["\\]/g, '\\$&');
  	return document.querySelector('[data-chat-anchor-key="' + esc(String(key)) + '"]');
  }

  function scrollportOf(row) {
  	if (!row) return null;
  	return row.closest('[data-conversation-scroll]') || row.closest('[data-slot="conversation"]') || null;
  }

  // Scroll the transcript so `row` sits at the top of the viewport-ish area.
  function scrollRowIntoView(row, offsetTop = 90) {
  	if (!row) return false;
  	const port = scrollportOf(row);
  	if (!port) { try { row.scrollIntoView({ block: 'start' }); } catch (_e) {} return true; }
  	const rowTop = row.getBoundingClientRect().top;
  	const portTop = port.getBoundingClientRect().top;
  	const delta = rowTop - portTop - offsetTop;
  	port.scrollTop += delta;
  	return true;
  }

  const flashTimers = new Map();
  function flashRow(row) {
  	if (!row) return;
  	const el = row;
  	el.setAttribute('dsh-chat-index-flash', '');
  	const t = flashTimers.get(el);
  	if (t) clearTimeout(t);
  	flashTimers.set(el, setTimeout(() => {
  		el.removeAttribute('dsh-chat-index-flash');
  		flashTimers.delete(el);
  	}, 1600));
  }

  // Wait a bounded number of animation frames for a predicate, then resolve.
  function waitFrames(predicate, maxFrames = 60) {
  	return new Promise((resolve) => {
  		let frames = 0;
  		const tick = () => {
  			if (predicate()) return resolve(true);
  			if (++frames >= maxFrames) return resolve(false);
  			requestAnimationFrame(tick);
  		};
  		tick();
  	});
  }

  //#endregion
  //#region src/client/03-data.js
  // Data layer: question index over session history.
  //
  // The live ConversationSnapshot only covers the currently loaded window, so
  // the full question list (and every branch session's list) is built from the
  // durable host log via the same RPC the product uses when it opens a session
  // window: api.sessions.history({ sessionId, beforeSeq, maxMessages }).
  // Everything here is defensive: unknown shapes, dropped pages and aborted
  // fetches degrade to whatever we already have instead of crashing the UI.

  const DATA_PAGE = 150;          // history RPC maxMessages per page
  const MAX_PAGES = 10;           // safety cap per session
  const MAX_QUESTIONS = 400;      // safety cap on stored questions per session
  const MAX_CHILDREN = 30;        // breadth cap for descendant walk

  // A user question as we present it in the index.
  // { seq, time, text }
  function isUserQuestionEvent(event) {
  	if (!event || typeof event !== 'object') return false;
  	const src = event.data && event.data.source;
  	return event.type === 'user/message' && (!src || src.kind === 'user');
  }

  function eventToQuestion(event) {
  	return {
  		seq: typeof event.seq === 'number' ? event.seq : 0,
  		time: typeof event.time === 'number' ? event.time : 0,
  		text: plainTextOf(event.data && event.data.content),
  	};
  }

  function sortAsc(a, b) { return a.seq - b.seq; }

  // Walk history pages newest-first, collect ascending user questions.
  // Resolves { questions, truncated } — never throws.
  async function historyQuestionsOf(api, sessionId, opts = {}) {
  	const maxPages = opts.maxPages || MAX_PAGES;
  	const cap = opts.cap || MAX_QUESTIONS;
  	const out = [];
  	let beforeSeq;
  	let truncated = false;
  	let hasMore = true;
  	let warned = false;
  	try {
  		for (let page = 0; page < maxPages && hasMore && out.length < cap; page++) {
  			const response = await api.sessions.history({
  				sessionId,
  				...(beforeSeq === undefined ? {} : { beforeSeq }),
  				maxMessages: DATA_PAGE,
  			});
  			// Client API envelope: { rpcId, result: { ok, value } }.
  			const result = response && response.result;
  			if (!result || result.ok !== true) {
  				if (!warned) {
  					warned = true;
  					console.warn('[dsh-chat-index] history error for', sessionId,
  						result && result.error ? result.error.code : 'no-result');
  				}
  				break;
  			}
  			const value = result.value || {};
  			const events = value.events;
  			if (!Array.isArray(events) || events.length === 0) break;
  			let oldestSeq = Infinity;
  			let newestSeq = -Infinity;
  			for (const entry of events) {
  				const event = entry && entry.event ? entry.event : entry;
  				if (!event || typeof event.seq !== 'number') continue;
  				if (event.seq < oldestSeq) oldestSeq = event.seq;
  				if (event.seq > newestSeq) newestSeq = event.seq;
  				if (isUserQuestionEvent(event)) out.push(eventToQuestion(event));
  			}
  			hasMore = value.hasMore === true && events.length >= DATA_PAGE;
  			if (beforeSeq !== undefined && newestSeq >= beforeSeq) {
  				// Safety: the server ignored our beforeSeq (should not happen).
  				truncated = true;
  				break;
  			}
  			beforeSeq = oldestSeq - 1;
  		}
  		if (out.length >= cap) truncated = true;
  	} catch (err) {
  		// Aborted or unauthorized — caller keeps whatever it had.
  		console.warn('[dsh-chat-index] history read failed for', sessionId, err);
  	}
  	const dedupe = new Map();
  	for (const q of out) if (!dedupe.has(q.seq)) dedupe.set(q.seq, q);
  	const questions = [...dedupe.values()].sort(sortAsc);
  	return { questions, truncated };
  }

  // Walk descendant sessions (child -> grandchild …) from a SessionListState
  // byId map (rows have parentSessionId / displayTitle / id).
  function collectDescendants(byId, rootId) {
  	const rows = [];
  	const seen = new Set([rootId]);
  	const walk = (parentId, depth) => {
  		if (rows.length >= MAX_CHILDREN || depth > 6) return;
  		const children = [];
  		for (const id of Object.keys(byId)) {
  			if (seen.has(id)) continue;
  			const row = byId[id];
  			// Client SessionSummary names the parent link parentId (older wire
  			// variants parentSessionId); accept both.
  			const link = row ? (row.parentId !== undefined ? row.parentId : row.parentSessionId) : undefined;
  			if (row && link === parentId) children.push({ id, row });
  		}
  		children.sort((a, b) => (a.row.updatedAt || 0) - (b.row.updatedAt || 0));
  		for (const { id, row } of children) {
  			if (seen.has(id) || rows.length >= MAX_CHILDREN) continue;
  			seen.add(id);
  			rows.push({
  				sessionId: id,
  				parentId,
  				depth,
  				title: (row.title || row.displayTitle || '').trim() || shortId(id),
  				updatedAt: row.updatedAt || 0,
  			});
  			walk(id, depth + 1);
  		}
  	};
  	walk(rootId, 0);
  	return rows;
  }

  function shortId(id) {
  	const s = String(id || '');
  	return s.length > 12 ? s.slice(0, 4) + '…' + s.slice(-4) : s;
  }

  // Full index payload for one root session: its own questions plus one entry
  // per descendant with that session's questions. Never throws.
  async function fetchIndex(api, sessionId, rowsById, signal) {
  	const mainPromise = historyQuestionsOf(api, sessionId, { maxPages: optsMaxPages(), cap: MAX_QUESTIONS });
  	const descendants = collectDescendants(rowsById || {}, sessionId);
  	const childResults = await Promise.all(descendants.map(async (desc) => {
  		if (signal && signal.aborted) return { desc, questions: [], truncated: false };
  		const r = await historyQuestionsOf(api, desc.sessionId, { maxPages: 6, cap: 120 });
  		return { desc, ...r };
  	}));
  	let main;
  	try { main = await mainPromise; } catch (_e) { main = { questions: [], truncated: false }; }
  	return {
  		sessionId,
  		main,
  		descendants: childResults.map((c) => ({ ...c.desc, questions: c.questions, truncated: c.truncated })),
  	};
  }

  function optsMaxPages() {
  	// Keep this separate so tuning needs no knowledge of the caller.
  	return MAX_PAGES;
  }

  // Merge live window questions (seq/time/text from ChatSnapshot nodes) into an
  // existing ascending question list without duplicating seqs.
  function mergeLive(questions, liveNodes) {
  	if (!liveNodes || liveNodes.length === 0) return questions;
  	const map = new Map(questions.map((q) => [q.seq, q]));
  	let changed = false;
  	for (const n of liveNodes) {
  		if (!map.has(n.seq)) {
  			map.set(n.seq, { seq: n.seq, time: n.time, text: plainTextOf(n.content) });
  			changed = true;
  		}
  	}
  	if (!changed) return questions;
  	return [...map.values()].sort(sortAsc);
  }

  //#endregion
  //#region src/client/04-components.js
  // React components: question index rail + chain panel (root overlay) plus a
  // per-session header toggle.
  //
  // Overlay mounts from shell.overlay (list/root). Root scope gives no useSession,
  // so the current real session and its live ConversationSnapshot come from the
  // sessions service: useSessions (SessionListState) for the current id, and
  // ctx.sessions.binding(id).session (SessionFace = ObservableSnapshot) consumed
  // with useSyncExternalStore.

  const RAIL_W = 28;          // rail width in px
  const RAIL_GUTTER = 12;     // spacing from the conversation column edge
  const PANEL_MAX_W = 420;

  function ciLog(...args) {
  	try { console.log('[dsh-chat-index]', ...args); } catch (_e) { /* noop */ }
  }

  class Boundary extends ReactLib.Component {
  	constructor(props) {
  		super(props);
  		this.state = { error: null };
  	}
  	static getDerivedStateFromError(error) {
  		return { error };
  	}
  	componentDidCatch(error, info) {
  		console.error('[dsh-chat-index] render error:', error, info);
  	}
  	render() {
  		if (this.state.error) return null;
  		return this.props.children;
  	}
  }

  // ---- shared open-state across the overlay (root) and the header toggle (session) ----
  const openBySession = new Map();     // sessionId -> boolean
  const openListeners = new Set();     // (sessionId, open) => void
  function panelOpenFor(sessionId) {
  	return sessionId ? openBySession.get(sessionId) === true : false;
  }
  function setPanelOpen(sessionId, open) {
  	if (!sessionId) return;
  	openBySession.set(sessionId, !!open);
  	for (const fn of openListeners) {
  		try { fn(sessionId, !!open); } catch (_e) { /* noop */ }
  	}
  }

  // Module-level "jump request": survives re-renders and session switches.
  let jumpRequest = null;     // { sessionId, seq, token }
  let jumpToken = 0;

  function useColumnBox() {
  	const [box, setBox] = useState(null);
  	useEffect(() => {
  		let raf = 0;
  		const measure = () => {
  			cancelAnimationFrame(raf);
  			raf = requestAnimationFrame(() => {
  				const next = measureBox();
  				setBox((prev) => (prev
  					&& prev.top === next.top && prev.right === next.right
  					&& prev.bottom === next.bottom && prev.left === next.left
  					? prev : next));
  			});
  		};
  		measure();
  		window.addEventListener('resize', measure);
  		const col = conversationColumn();
  		let ro;
  		if (col && typeof ResizeObserver !== 'undefined') {
  			try { ro = new ResizeObserver(measure); ro.observe(col); } catch (_e) { /* noop */ }
  		}
  		const iv = setInterval(measure, 1200);
  		return () => {
  			cancelAnimationFrame(raf);
  			window.removeEventListener('resize', measure);
  			if (ro) ro.disconnect();
  			clearInterval(iv);
  		};
  	}, []);
  	return box;
  }

  function QuestionIndexOverlay(props) {
  	const { ctx, useSessions } = props;
  	const box = useColumnBox();

  	const listState = useSessions((s) => s);
  	const current = useMemo(() => (
  		listState && listState.current !== undefined
  			&& listState.byId[listState.current] && !listState.byId[listState.current].blank
  			? listState.current : undefined
  	), [listState]);
  	const sessionRef = useRef(current);
  	sessionRef.current = current;

  	// Live ConversationSnapshot of the current session.
  	const faceRef = useRef(null);
  	const [face, setFace] = useState(null);
  	useEffect(() => {
  		let mounted = true;
  		let next = null;
  		if (current) {
  			try {
  				const binding = ctx.sessions.binding(current);
  				if (binding && binding.session) next = binding.session;
  			} catch (err) {
  				console.warn('[dsh-chat-index] binding failed', current, err);
  			}
  		}
  		faceRef.current = next;
  		if (mounted) setFace(next);
  		return () => { mounted = false; };
  	}, [current, ctx]);
  	useEffect(() => { faceRef.current = face; }, [face]);

  	const subscribe = useCallback((cb) => {
  		const f = faceRef.current;
  		return f && typeof f.subscribe === 'function' ? f.subscribe(cb) : () => {};
  	}, []);
  	const getSnapshot = useCallback(() => {
  		const f = faceRef.current;
  		if (!f || typeof f.getSnapshot !== 'function') return undefined;
  		try { return f.getSnapshot(); } catch (_e) { return undefined; }
  	}, []);
  	const snapshot = useSyncExternalStore(subscribe, getSnapshot);
  	const chat = snapshot && snapshot.openState === 'open' ? snapshot.chat : undefined;
  	const liveNodes = snapshot && snapshot.openState === 'open'
  		? snapshot.nodes.filter((n) => n.kind === 'user' || n.kind === 'steering')
  		: undefined;

  	const liveQuestions = useMemo(() => (liveNodes || []).map((n) => ({
  		seq: n.seq,
  		time: n.time,
  		text: plainTextOf(n.content),
  	})).sort((a, b) => a.seq - b.seq), [liveNodes]);

  	const [fullMain, setFullMain] = useState(null);
  	const [branchRows, setBranchRows] = useState([]);
  	const [branchData, setBranchData] = useState(null);
  	const [loadState, setLoadState] = useState('idle');
  	const [expanded, setExpanded] = useState(false);
  	const [jumpTick, setJumpTick] = useState(0);

  	// Per-session reset + open-state sync from the shared map / header toggle.
  	useEffect(() => {
  		setFullMain(null);
  		setBranchRows([]);
  		setBranchData(null);
  		setLoadState('idle');
  		setExpanded(panelOpenFor(current));
  	}, [current]);
  	useEffect(() => {
  		const fn = (sessionId, open) => { if (sessionId === sessionRef.current) setExpanded(open); };
  		openListeners.add(fn);
  		return () => { openListeners.delete(fn); };
  	}, []);

  	// Full-history load (main thread + descendants).
  	useEffect(() => {
  		if (!current) return;
  		const ac = new AbortController();
  		let cancelled = false;
  		const run = async () => {
  			const api = ctx && ctx.connection && ctx.connection.api ? ctx.connection.api : null;
  			if (!api) { setLoadState('done'); return; }
  			setLoadState('loading');
  			try {
  				const byId = (listState && listState.byId) || {};
  				const payload = await fetchIndex(api, current, byId, ac.signal);
  				if (cancelled || ac.signal.aborted) return;
  				setFullMain(payload.main.questions);
  				setBranchRows(payload.descendants.map((d) => ({
  					sessionId: d.sessionId, parentId: d.parentId, depth: d.depth,
  					title: d.title, updatedAt: d.updatedAt,
  				})));
  				const map = {};
  				for (const d of payload.descendants) map[d.sessionId] = {
  					questions: d.questions, truncated: d.truncated, depth: d.depth,
  					title: d.title, parentId: d.parentId, updatedAt: d.updatedAt,
  				};
  				setBranchData(map);
  				setLoadState('done');
  			} catch (err) {
  				if (!cancelled && !ac.signal.aborted) { setLoadState('error'); console.warn('[dsh-chat-index] index load failed', err); }
  			}
  		};
  		run();
  		return () => { cancelled = true; ac.abort(); };
  		// eslint-disable-next-line react-hooks/exhaustive-deps
  	}, [current]);

  	const displayMain = useMemo(() => {
  		if (fullMain) return mergeLive(fullMain, liveQuestions);
  		return liveQuestions;
  	}, [fullMain, liveQuestions]);

  	const hasLiveOnly = !fullMain;

  	const performJump = useCallback((targetSessionId, seq) => {
  		if (typeof seq !== 'number') return;
  		const target = targetSessionId || sessionRef.current;
  		if (!target) return;
  		jumpRequest = { sessionId: target, seq, token: ++jumpToken };
  		setJumpTick((t) => t + 1);
  		if (target !== sessionRef.current) {
  			try {
  				ctx.sessions.open(target);
  			} catch (err) {
  				console.warn('[dsh-chat-index] open failed', target, err);
  				jumpRequest = null;
  			}
  		}
  	}, [ctx]);

  	// Consume a pending jump once the target window is open.
  	useEffect(() => {
  		const req = jumpRequest;
  		if (!req || req.sessionId !== sessionRef.current) return;
  		if (!chat) return;
  		let stopped = false;
  		let iterations = 0;
  		let pagesLoaded = 0;
  		const attempt = async () => {
  			if (stopped) return;
  			iterations++;
  			const key = seqToAnchorKey(chat, req.seq);
  			const row = key ? rowByAnchorKey(key) : null;
  			if (row) {
  				scrollRowIntoView(row, 72);
  				flashRow(row);
  				if (jumpRequest === req) jumpRequest = null;
  				return;
  			}
  			if (iterations < 50 && pagesLoaded < 10) {
  				try {
  					const binding = ctx.sessions && ctx.sessions.binding ? ctx.sessions.binding(req.sessionId) : undefined;
  					if (binding && binding.session && typeof binding.session.loadOlder === 'function') {
  						pagesLoaded++;
  						await binding.session.loadOlder();
  					}
  				} catch (_e) { /* loadOlder unavailable */ }
  				setTimeout(() => attempt(), 110);
  			} else {
  				if (jumpRequest === req) jumpRequest = null;
  			}
  		};
  		attempt();
  		return () => { stopped = true; };
  	}, [jumpTick, chat, current, ctx]);

  	const geo = useMemo(() => {
  		if (!box) return null;
  		const right = Math.min(box.right, window.innerWidth);
  		const left = Math.max(box.left, 0);
  		const top = box.top + 56;
  		const bottom = box.bottom - 180;
  		if (bottom <= top + 40) return null;
  		const railRight = right - RAIL_GUTTER;
  		const railLeft = railRight - RAIL_W;
  		const panelWidth = Math.min(PANEL_MAX_W, Math.max(260, box.width * 0.44));
  		const panelRight = railLeft - 8;
  		const panelLeft = Math.max(left + 8, panelRight - panelWidth);
  		return {
  			railLeft, railTop: top, railRight, railBottom: bottom,
  			panelLeft, panelTop: top + 4, panelRight, panelBottom: bottom + 56,
  			panelWidth: panelRight - panelLeft,
  		};
  	}, [box]);

  	const hasQuestions = displayMain.length > 0;
  	const expandedByRequest = expanded && geo;

  	const root = useMemo(() => {
  		if (!geo) return null;
  		const children = [];
  		if (expandedByRequest) {
  			children.push(h(Panel, {
  				key: 'panel',
  				geo,
  				mainQuestions: displayMain,
  				hasLiveOnly,
  				branchRows,
  				branchData,
  				loadState,
  				onJump: performJump,
  				onCollapse: () => setPanelOpen(sessionRef.current, false),
  			}));
  		} else if (hasQuestions) {
  			children.push(h(Rail, {
  				key: 'rail',
  				geo,
  				questions: displayMain,
  				hasLiveOnly,
  				currentSeq: latestSeq(liveQuestions),
  				onJump: performJump,
  				onExpand: () => setPanelOpen(sessionRef.current, true),
  			}));
  		}
  		return children.length ? h(Fragment, null, children) : null;
  		// eslint-disable-next-line react-hooks/exhaustive-deps
  	}, [geo, expandedByRequest, hasQuestions, displayMain, hasLiveOnly, branchRows, branchData, loadState, liveQuestions, performJump]);

  	const loggedRef = useRef(null);
  	if (loggedRef.current !== (current || 'none')) {
  		loggedRef.current = current || 'none';
  		ciLog('overlay', { current, questions: displayMain.length, load: loadState, liveOnly: hasLiveOnly });
  	}

  	if (!root) return null;
  	const content = h('div', {
  		'dsh-chat-index-root': '',
  		style: { pointerEvents: 'none', position: 'fixed', inset: 0, zIndex: 9000 },
  	}, h(Boundary, { key: 'boundary' }, root));
  	return ReactDOMLib && ReactDOMLib.createPortal
  		? ReactDOMLib.createPortal(content, document.body)
  		: content;
  }

  function latestSeq(questions) {
  	let m = -1;
  	for (const q of questions) if (q.seq > m) m = q.seq;
  	return m < 0 ? undefined : m;
  }

  // ---- rail: time-proportional dots + scrub ----
  function Rail(props) {
  	const { geo, questions, hasLiveOnly, currentSeq, onJump, onExpand } = props;
  	const [scrub, setScrub] = useState(null);
  	const trackRef = useRef(null);

  	const count = questions.length;
  	const height = Math.max(10, geo.railBottom - geo.railTop);
  	const usable = Math.max(4, height - 16);

  	// Time extent of the whole question list.
  	let minT = Infinity;
  	let maxT = -Infinity;
  	for (const q of questions) {
  		const t = typeof q.time === 'number' && q.time > 0 ? q.time : q.seq;
  		if (t < minT) minT = t;
  		if (t > maxT) maxT = t;
  	}
  	const span = maxT - minT || 1;
  	const yOfTime = (t) => 8 + ((t - minT) / span) * usable;
  	const timeAtY = (y) => minT + ((y - 8) / usable) * span;

  	// Sample at most ~70 markers; positions follow time, so visual gaps match
  	// real time gaps between questions.
  	const markers = [];
  	if (count <= 70) {
  		for (const q of questions) markers.push(q);
  	} else {
  		const slotCount = 70;
  		const used = new Set();
  		for (let i = 0; i < slotCount; i++) {
  			const targetT = minT + (i * span) / (slotCount - 1);
  			let best = -1;
  			let bestD = Infinity;
  			for (let j = 0; j < count; j++) {
  				if (used.has(j)) continue;
  				const t = typeof questions[j].time === 'number' && questions[j].time > 0 ? questions[j].time : questions[j].seq;
  				const d = Math.abs(t - targetT);
  				if (d < bestD) { bestD = d; best = j; }
  			}
  			if (best >= 0) { used.add(best); markers.push(questions[best]); }
  		}
  		const last = questions[count - 1];
  		if (last && markers[markers.length - 1].seq !== last.seq) markers.push(last);
  	}
  	markers.sort((a, b) => a.seq - b.seq);

  	const indexAt = (clientY) => {
  		const r = trackRef.current ? trackRef.current.getBoundingClientRect() : null;
  		if (!r || count === 0) return 0;
  		const frac = Math.min(1, Math.max(0, (clientY - r.top - 8) / usable));
  		const targetT = minT + frac * span;
  		let best = 0;
  		let bestD = Infinity;
  		for (let i = 0; i < count; i++) {
  			const t = typeof questions[i].time === 'number' && questions[i].time > 0 ? questions[i].time : questions[i].seq;
  			const d = Math.abs(t - targetT);
  			if (d < bestD) { bestD = d; best = i; }
  		}
  		return best;
  	};

  	const onPointerDown = (e) => {
  		setScrub({ index: indexAt(e.clientY) });
  		e.currentTarget.setPointerCapture && e.currentTarget.setPointerCapture(e.pointerId);
  	};
  	const onPointerMove = (e) => {
  		if (!scrub) return;
  		setScrub({ index: indexAt(e.clientY) });
  	};
  	const endScrub = () => {
  		if (scrub) {
  			const q = questions[scrub.index];
  			setScrub(null);
  			if (q) onJump(null, q.seq);
  		}
  	};

  	const flyout = scrub ? questions[scrub.index] : undefined;
  	const flyTime = (q) => (typeof q.time === 'number' && q.time > 0 ? q.time : q.seq);

  	const railChildren = [];
  	railChildren.push(h('div', {
  		key: 'head',
  		'dsh-chat-index-rail-head': '',
  		title: count + ' 个提问（悬停看摘要，点按跳转，拖动快速滑动）',
  	}, String(count)));
  	railChildren.push(h('div', {
  		key: 'track',
  		'dsh-chat-index-track': '',
  		ref: trackRef,
  		onPointerDown,
  		onPointerMove,
  		onPointerUp: endScrub,
  		onPointerCancel: endScrub,
  		style: { height: height + 'px' },
  	}, markers.map((q) => h('div', {
  			key: 'm' + q.seq,
  			'dsh-chat-index-marker': '',
  			...(q.seq === currentSeq ? { 'dsh-chat-index-current': '' } : {}),
  			style: { top: yOfTime(flyTime(q)) + 'px' },
  			title: formatTime(q.time) + '\n' + q.text,
  			onClick: (e) => { e.stopPropagation(); onJump(null, q.seq); },
  			onPointerDown: (e) => e.stopPropagation(),
  		}))));
  	railChildren.push(h('button', {
  		key: 'toggle',
  		type: 'button',
  		'dsh-chat-index-toggle': '',
  		title: '展开提问链',
  		onClick: (e) => { e.stopPropagation(); onExpand(); },
  	}, '⇱'));

  	const railStyle = {
  		position: 'fixed',
  		left: geo.railLeft + 'px',
  		top: geo.railTop + 'px',
  		width: RAIL_W + 'px',
  		height: height + 'px',
  		pointerEvents: 'auto',
  		zIndex: 9001,
  	};
  	return h(Fragment, null,
  		h('div', { 'dsh-chat-index-rail': '', style: railStyle }, railChildren),
  		flyout ? h('div', {
  			'dsh-chat-index-flyout': '',
  			style: { top: (geo.railTop + yOfTime(flyTime(flyout))) + 'px' },
  		},
  			h('div', null, formatTime(flyout.time)),
  			h('div', null, flyout.text)) : null,
  	);
  }

  // ---- expanded chain panel ----
  function Panel(props) {
  	const { geo, mainQuestions, branchRows, branchData, loadState, onJump, onCollapse } = props;
  	const branches = branchRows.filter((b) => b.depth === 0);
  	const nested = branchRows.filter((b) => b.depth > 0);

  	const style = {
  		position: 'fixed',
  		left: geo.panelLeft + 'px',
  		top: geo.panelTop + 'px',
  		width: geo.panelWidth + 'px',
  		height: Math.max(140, geo.panelBottom - geo.panelTop) + 'px',
  		pointerEvents: 'auto',
  		zIndex: 9002,
  	};

  	const total = mainQuestions.length + branchRows.reduce((n, b) => n + ((branchData && branchData[b.sessionId] && branchData[b.sessionId].questions) || []).length, 0);
  	const head = h('div', { 'dsh-chat-index-panel-head': '' },
  		h('span', null, '提问索引'),
  		h('span', { style: { opacity: 0.6, fontWeight: 400, fontSize: 11 } }, ' · ' + total),
  		loadState === 'loading' ? h('span', { style: { opacity: 0.6, fontWeight: 400, fontSize: 11 } }, '…') : null,
  		h('span', { style: { flex: 1 } }),
  		h('button', { type: 'button', title: '收起', 'dsh-chat-index-toggle': '', onClick: onCollapse }, '✕'),
  	);

  	let body;
  	const isEmpty = mainQuestions.length === 0 && branchRows.length === 0;
  	if (isEmpty) {
  		body = h('div', { style: { padding: 14, opacity: 0.7 } }, loadState === 'loading' ? '加载中…' : '这个会话还没有提问。');
  	} else {
  		const list = [];
  		for (const q of mainQuestions) {
  			list.push(h(QuestionRow, { key: 'm' + q.seq, q, depth: 0, onJump: () => onJump(null, q.seq) }));
  		}
  		const renderBranch = (b, depth) => {
  			const data = branchData && branchData[b.sessionId];
  			const questions = (data && data.questions) || [];
  			const kids = [];
  			for (const c of branchRows) if (c.parentId === b.sessionId) kids.push(c);
  			const titleExtra = b.updatedAt ? ' · ' + formatTime(b.updatedAt) : '';
  			const row = h('div', { key: 'b' + b.sessionId, 'dsh-chat-index-node': '', style: { '--depth': String(depth) } },
  				h('div', {
  					'dsh-chat-index-node-row': '',
  					title: '分支会话：' + b.title + titleExtra,
  					onClick: () => (questions[0] ? onJump(b.sessionId, questions[0].seq) : undefined),
  				},
  					h('span', { 'dsh-chat-index-branch-tag': '' }, '分支'),
  					h('span', { 'dsh-chat-index-node-text': '' },
  						h('div', { 'dsh-chat-index-node-q': '' }, b.title),
  						h('div', { 'dsh-chat-index-node-meta': '' }, questions.length ? questions.length + ' 个提问' : '无提问' + titleExtra)),
  				),
  				questions.map((q) => h(QuestionRow, {
  					key: 'bq' + b.sessionId + q.seq,
  					q,
  					depth: depth + 1,
  					onJump: () => onJump(b.sessionId, q.seq),
  				})),
  				kids.map((c) => renderBranch(c, depth + 1)),
  			);
  			return row;
  		};
  		for (const b of branches) list.push(renderBranch(b, 1));
  		if (nested.length > 0 && branches.length === 0) {
  			for (const b of nested) list.push(renderBranch(b, 1));
  		}
  		body = h('div', { 'dsh-chat-index-panel-body': '' }, list);
  	}

  	return h('div', { 'dsh-chat-index-panel': '', style }, head, body);
  }

  function QuestionRow(props) {
  	const { q, depth, onJump } = props;
  	return h('div', { 'dsh-chat-index-node': '', style: { '--depth': String(depth) } },
  		h('div', {
  			'dsh-chat-index-node-row': '',
  			onClick: onJump,
  			title: formatTime(q.time) + '\n' + q.text,
  		},
  			h('span', { 'dsh-chat-index-node-dot': '' }),
  			h('span', { 'dsh-chat-index-node-text': '' },
  				h('div', { 'dsh-chat-index-node-q': '' }, q.text),
  				h('div', { 'dsh-chat-index-node-meta': '' }, formatTime(q.time)),
  			),
  		));
  }

  // ---- header toggle (session scope): always-visible entry point ----
  function HeaderIndexToggle(props) {
  	const { sessionId } = props;
  	const open = panelOpenFor(sessionId);
  	return h('button', {
  		type: 'button',
  		title: '提问索引' + (open ? '（收起）' : ''),
  		'aria-label': '提问索引',
  		style: {
  			cursor: 'pointer',
  			display: 'inline-flex',
  			alignItems: 'center',
  			justifyContent: 'center',
  			width: 26,
  			height: 26,
  			borderRadius: 7,
  			border: '1px solid color-mix(in srgb, currentColor 22%, transparent)',
  			background: open ? 'color-mix(in srgb, currentColor 14%, transparent)' : 'transparent',
  			color: 'inherit',
  			fontSize: 13,
  			lineHeight: 1,
  		},
  		onClick: () => setPanelOpen(sessionId, !open),
  	}, '≡');
  }

  //#endregion
  //#region src/client/05-apply.js
  // Plugin definition: registers the root overlay (rail + chain panel) and a
  // per-session header toggle that opens the panel for that session.
  let pluginCtx = null;

  const name = 'dsh-chat-index';
  const inject = ['slots', 'sessions', 'connection'];

  function apply(ctx) {
  	pluginCtx = ctx;
  	try { ensureChatIndexStyle(); } catch (err) { console.warn('[dsh-chat-index] style install failed', err); }
  	ciLog('apply');

  	// Root overlay: the rail (when the session has questions) and the chain
  	// panel, both portaled to document.body.
  	ctx.slots.inject('shell.overlay', function* () {
  		yield ctx.slots.register({
  			name: 'shell.overlay',
  			id: 'chat-index-overlay',
  			order: 500,
  		}, (props) => h(QuestionIndexOverlay, Object.assign({ ctx }, props)));
  	});

  	// Header toggle: an always-present "≡" in the right-aligned session
  	// header utilities that opens/closes the panel for the current session.
  	ctx.slots.inject('conversation.session.header.utilities', function* () {
  		yield ctx.slots.register({
  			name: 'conversation.session.header.utilities',
  			id: 'chat-index-header-toggle',
  			order: 10,
  		}, (props) => h(HeaderIndexToggle, Object.assign({ ctx }, props)));
  	});

  	if (typeof window !== 'undefined') window.__dshChatIndexDebug = { applied: true, at: Date.now() };
  }

  //#endregion

		module.exports = { apply, inject, name };
		return module.exports;
	}
});
