// dsh-chat-index build script.
//
// Produces lib/client.js (the DSH browser client module) by concatenating the
// plain-JS fragments in src/client/*.js (lexical order) and wrapping them in
// the `window.__ModuleLoader__.load({ id, factory })` contract used by the
// DeepSeek Harness web module system. No transpilation: fragments must be
// plain modern JavaScript (no JSX/TS) and run inside the factory closure,
// where `require` resolves react / graph-row packages / shell seed modules.
import { readdir, readFile, writeFile, rm } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const srcDir = join(root, 'src', 'client');
const outFile = join(root, 'lib', 'client.js');
const id = 'dsh-chat-index';

async function build() {
  const names = (await readdir(srcDir)).filter((n) => n.endsWith('.js')).sort();
  let body = '';
  for (const name of names) {
    body += `//#region src/client/${name}\n`;
    body += await readFile(join(srcDir, name), 'utf8');
    body += `\n//#endregion\n`;
  }
  const out = `// dsh-chat-index client bundle (generated by scripts/build.mjs — edit src/client/*, not this file)
window.__ModuleLoader__.load({
	id: ${JSON.stringify(id)},
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
${indent(body, 2)}
		module.exports = { apply, inject, name };
		return module.exports;
	}
});
`;
  await writeFile(outFile, out, 'utf8');
  console.log(`[build] wrote ${outFile} (${out.length} bytes, ${names.length} fragments)`);
}

function indent(text, spaces) {
  const pad = ' '.repeat(spaces);
  return text
    .split('\n')
    .map((line) => (line.length ? pad + line : line))
    .join('\n');
}

await build();
